2016-09-08 16:18:01 Error: Fatal Error (1): Class 'DispatcherFactory' not found in [C:\xampp\htdocs\cakephp\config\bootstrap.php, line 224]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 98
[main] - [internal], line ??



2016-09-08 16:18:01 Error: [Cake\Error\FatalErrorException] Class 'DispatcherFactory' not found
Stack Trace:
#0 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(98): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Class 'Dispatch...', 'C:\\xampp\\htdocs...', 224)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2016-09-14 03:06:57 Error: Fatal Error (1): Class 'Route' not found in [C:\xampp\htdocs\cakephp\config\routes.php, line 78]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 98
[main] - [internal], line ??



2016-09-14 03:06:58 Error: [Cake\Error\FatalErrorException] Class 'Route' not found
Stack Trace:
#0 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(98): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Class 'Route' n...', 'C:\\xampp\\htdocs...', 78)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2016-09-14 03:10:52 Error: Fatal Error (4): syntax error, unexpected 'controller' (T_STRING) in [C:\xampp\htdocs\cakephp\config\routes.php, line 80]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 98
[main] - [internal], line ??



2016-09-14 03:10:52 Error: [Cake\Error\FatalErrorException] syntax error, unexpected 'controller' (T_STRING)
Stack Trace:
#0 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(98): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 80)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2016-09-14 03:11:26 Error: Fatal Error (4): syntax error, unexpected '}' in [C:\xampp\htdocs\cakephp\config\routes.php, line 81]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 98
[main] - [internal], line ??



2016-09-14 03:11:26 Error: [Cake\Error\FatalErrorException] syntax error, unexpected '}'
Stack Trace:
#0 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(98): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 81)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2016-09-14 03:11:27 Error: Fatal Error (4): syntax error, unexpected '}' in [C:\xampp\htdocs\cakephp\config\routes.php, line 81]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 98
[main] - [internal], line ??



2016-09-14 03:11:27 Error: [Cake\Error\FatalErrorException] syntax error, unexpected '}'
Stack Trace:
#0 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(98): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 81)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2016-09-14 03:12:26 Error: Fatal Error (4): syntax error, unexpected '}' in [C:\xampp\htdocs\cakephp\config\routes.php, line 81]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 98
[main] - [internal], line ??



2016-09-14 03:12:26 Error: [Cake\Error\FatalErrorException] syntax error, unexpected '}'
Stack Trace:
#0 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(98): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 81)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2016-09-14 03:15:39 Error: Fatal Error (4): syntax error, unexpected ',' in [C:\xampp\htdocs\cakephp\config\routes.php, line 81]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 98
[main] - [internal], line ??



2016-09-14 03:15:39 Error: [Cake\Error\FatalErrorException] syntax error, unexpected ','
Stack Trace:
#0 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(98): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 81)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2016-09-14 03:16:18 Warning: Warning (2): Missing argument 1 for App\Controller\UsersController::view() in [C:\xampp\htdocs\cakephp\src\Controller\UsersController.php, line 17]
Request URL: /cakephp/users/view
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 146
App\Controller\UsersController::view() - APP/Controller\UsersController.php, line 17
Cake\Controller\Controller::invokeAction() - CORE\src\Controller\Controller.php, line 435
Cake\Http\ActionDispatcher::_invoke() - CORE\src\Http\ActionDispatcher.php, line 122
Cake\Http\ActionDispatcher::dispatch() - CORE\src\Http\ActionDispatcher.php, line 96
Cake\Http\BaseApplication::__invoke() - CORE\src\Http\BaseApplication.php, line 83
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\RoutingMiddleware::__invoke() - CORE\src\Routing\Middleware\RoutingMiddleware.php, line 52
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\AssetMiddleware::__invoke() - CORE\src\Routing\Middleware\AssetMiddleware.php, line 88
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Error\Middleware\ErrorHandlerMiddleware::__invoke() - CORE\src\Error\Middleware\ErrorHandlerMiddleware.php, line 52
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Http\Runner::run() - CORE\src\Http\Runner.php, line 51
Cake\Http\Server::run() - CORE\src\Http\Server.php, line 82
[main] - ROOT\webroot\index.php, line 37



2016-09-14 03:17:18 Warning: Warning (2): Missing argument 1 for App\Controller\UsersController::view() in [C:\xampp\htdocs\cakephp\src\Controller\UsersController.php, line 17]
Request URL: /cakephp/users/view
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 146
App\Controller\UsersController::view() - APP/Controller\UsersController.php, line 17
Cake\Controller\Controller::invokeAction() - CORE\src\Controller\Controller.php, line 435
Cake\Http\ActionDispatcher::_invoke() - CORE\src\Http\ActionDispatcher.php, line 122
Cake\Http\ActionDispatcher::dispatch() - CORE\src\Http\ActionDispatcher.php, line 96
Cake\Http\BaseApplication::__invoke() - CORE\src\Http\BaseApplication.php, line 83
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\RoutingMiddleware::__invoke() - CORE\src\Routing\Middleware\RoutingMiddleware.php, line 52
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\AssetMiddleware::__invoke() - CORE\src\Routing\Middleware\AssetMiddleware.php, line 88
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Error\Middleware\ErrorHandlerMiddleware::__invoke() - CORE\src\Error\Middleware\ErrorHandlerMiddleware.php, line 52
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Http\Runner::run() - CORE\src\Http\Runner.php, line 51
Cake\Http\Server::run() - CORE\src\Http\Server.php, line 82
[main] - ROOT\webroot\index.php, line 37



2016-09-14 03:30:57 Error: Fatal Error (1): Call to a member function find() on boolean in [C:\xampp\htdocs\cakephp\src\Controller\UsersController.php, line 14]
Request URL: /cakephp/users/index
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 98
[main] - [internal], line ??



2016-09-14 03:30:57 Error: [Cake\Error\FatalErrorException] Call to a member function find() on boolean
Request URL: /cakephp/users/index
Stack Trace:
#0 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(98): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 14)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2016-09-14 03:35:22 Error: Fatal Error (1): Call to a member function find() on boolean in [C:\xampp\htdocs\cakephp\src\Controller\UsersController.php, line 14]
Request URL: /cakephp/users/index
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 98
[main] - [internal], line ??



2016-09-14 03:35:22 Error: [Cake\Error\FatalErrorException] Call to a member function find() on boolean
Request URL: /cakephp/users/index
Stack Trace:
#0 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(98): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 14)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2016-09-14 03:35:30 Error: Fatal Error (1): Call to a member function find() on boolean in [C:\xampp\htdocs\cakephp\src\Controller\UsersController.php, line 14]
Request URL: /cakephp/users/index
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 98
[main] - [internal], line ??



2016-09-14 03:35:30 Error: [Cake\Error\FatalErrorException] Call to a member function find() on boolean
Request URL: /cakephp/users/index
Stack Trace:
#0 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(98): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 14)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2016-09-14 03:36:49 Error: Fatal Error (1): Call to a member function find() on boolean in [C:\xampp\htdocs\cakephp\src\Controller\UsersController.php, line 14]
Request URL: /cakephp/users/index
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 98
[main] - [internal], line ??



2016-09-14 03:36:49 Error: [Cake\Error\FatalErrorException] Call to a member function find() on boolean
Request URL: /cakephp/users/index
Stack Trace:
#0 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(98): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 14)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2016-09-14 03:36:50 Error: Fatal Error (1): Call to a member function find() on boolean in [C:\xampp\htdocs\cakephp\src\Controller\UsersController.php, line 14]
Request URL: /cakephp/users/index
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 98
[main] - [internal], line ??



2016-09-14 03:36:50 Error: [Cake\Error\FatalErrorException] Call to a member function find() on boolean
Request URL: /cakephp/users/index
Stack Trace:
#0 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(98): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 14)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2016-09-14 03:38:51 Error: Fatal Error (1): Call to a member function find() on boolean in [C:\xampp\htdocs\cakephp\src\Controller\UsersController.php, line 14]
Request URL: /cakephp/users/index
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 98
[main] - [internal], line ??



2016-09-14 03:38:51 Error: [Cake\Error\FatalErrorException] Call to a member function find() on boolean
Request URL: /cakephp/users/index
Stack Trace:
#0 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(98): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 14)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2016-09-14 03:39:06 Error: Fatal Error (1): Call to a member function find() on boolean in [C:\xampp\htdocs\cakephp\src\Controller\UsersController.php, line 14]
Request URL: /cakephp/users
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 98
[main] - [internal], line ??



2016-09-14 03:39:06 Error: [Cake\Error\FatalErrorException] Call to a member function find() on boolean
Request URL: /cakephp/users
Stack Trace:
#0 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(98): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 14)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2016-09-14 03:43:21 Error: Fatal Error (1): Call to a member function find() on boolean in [C:\xampp\htdocs\cakephp\src\Controller\UsersController.php, line 14]
Request URL: /cakephp/users
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 98
[main] - [internal], line ??



2016-09-14 03:43:21 Error: [Cake\Error\FatalErrorException] Call to a member function find() on boolean
Request URL: /cakephp/users
Stack Trace:
#0 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(98): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 14)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2016-09-14 03:44:21 Error: Fatal Error (1): Call to a member function find() on boolean in [C:\xampp\htdocs\cakephp\src\Controller\UsersController.php, line 14]
Request URL: /cakephp/users/index
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 98
[main] - [internal], line ??



2016-09-14 03:44:21 Error: [Cake\Error\FatalErrorException] Call to a member function find() on boolean
Request URL: /cakephp/users/index
Stack Trace:
#0 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(98): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 14)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2016-09-14 03:45:01 Error: Fatal Error (4): syntax error, unexpected 'endforeach' (T_ENDFOREACH) in [C:\xampp\htdocs\cakephp\src\Template\Users\index.ctp, line 8]
Request URL: /cakephp/users/index
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 98
[main] - [internal], line ??



2016-09-14 03:45:01 Error: [Cake\Error\FatalErrorException] syntax error, unexpected 'endforeach' (T_ENDFOREACH)
Request URL: /cakephp/users/index
Stack Trace:
#0 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(98): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 8)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2016-09-14 03:45:04 Error: Fatal Error (4): syntax error, unexpected 'endforeach' (T_ENDFOREACH) in [C:\xampp\htdocs\cakephp\src\Template\Users\index.ctp, line 8]
Request URL: /cakephp/users/
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 98
[main] - [internal], line ??



2016-09-14 03:45:04 Error: [Cake\Error\FatalErrorException] syntax error, unexpected 'endforeach' (T_ENDFOREACH)
Request URL: /cakephp/users/
Stack Trace:
#0 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(98): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 8)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2016-09-14 03:47:14 Error: Fatal Error (1): Call to a member function find() on boolean in [C:\xampp\htdocs\cakephp\src\Controller\UsersController.php, line 14]
Request URL: /cakephp/users/
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 98
[main] - [internal], line ??



2016-09-14 03:47:14 Error: [Cake\Error\FatalErrorException] Call to a member function find() on boolean
Request URL: /cakephp/users/
Stack Trace:
#0 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(98): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 14)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2016-09-14 03:47:16 Error: Fatal Error (1): Call to a member function find() on boolean in [C:\xampp\htdocs\cakephp\src\Controller\UsersController.php, line 14]
Request URL: /cakephp/users/
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 98
[main] - [internal], line ??



2016-09-14 03:47:16 Error: [Cake\Error\FatalErrorException] Call to a member function find() on boolean
Request URL: /cakephp/users/
Stack Trace:
#0 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(98): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 14)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2016-09-14 03:47:20 Error: Fatal Error (1): Call to a member function find() on boolean in [C:\xampp\htdocs\cakephp\src\Controller\UsersController.php, line 14]
Request URL: /cakephp/users/index
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 98
[main] - [internal], line ??



2016-09-14 03:47:20 Error: [Cake\Error\FatalErrorException] Call to a member function find() on boolean
Request URL: /cakephp/users/index
Stack Trace:
#0 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(98): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 14)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2016-09-14 03:47:39 Error: Fatal Error (1): Call to a member function find() on boolean in [C:\xampp\htdocs\cakephp\src\Controller\UsersController.php, line 14]
Request URL: /cakephp/users/index
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 98
[main] - [internal], line ??



2016-09-14 03:47:39 Error: [Cake\Error\FatalErrorException] Call to a member function find() on boolean
Request URL: /cakephp/users/index
Stack Trace:
#0 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(98): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 14)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2016-09-14 06:39:20 Warning: Warning (2): Missing argument 1 for App\Controller\UsersController::view() in [C:\xampp\htdocs\cakephp\src\Controller\UsersController.php, line 17]
Request URL: /cakephp/users/view
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 146
App\Controller\UsersController::view() - APP/Controller\UsersController.php, line 17
Cake\Controller\Controller::invokeAction() - CORE\src\Controller\Controller.php, line 435
Cake\Http\ActionDispatcher::_invoke() - CORE\src\Http\ActionDispatcher.php, line 122
Cake\Http\ActionDispatcher::dispatch() - CORE\src\Http\ActionDispatcher.php, line 96
Cake\Http\BaseApplication::__invoke() - CORE\src\Http\BaseApplication.php, line 83
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\RoutingMiddleware::__invoke() - CORE\src\Routing\Middleware\RoutingMiddleware.php, line 52
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\AssetMiddleware::__invoke() - CORE\src\Routing\Middleware\AssetMiddleware.php, line 88
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Error\Middleware\ErrorHandlerMiddleware::__invoke() - CORE\src\Error\Middleware\ErrorHandlerMiddleware.php, line 52
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Http\Runner::run() - CORE\src\Http\Runner.php, line 51
Cake\Http\Server::run() - CORE\src\Http\Server.php, line 82
[main] - ROOT\webroot\index.php, line 37



2016-09-14 06:41:55 Error: Fatal Error (4): syntax error, unexpected '->' (T_OBJECT_OPERATOR) in [C:\xampp\htdocs\cakephp\src\Controller\UsersController.php, line 14]
Request URL: /cakephp/users/index
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 98
[main] - [internal], line ??



2016-09-14 06:41:55 Error: [Cake\Error\FatalErrorException] syntax error, unexpected '->' (T_OBJECT_OPERATOR)
Request URL: /cakephp/users/index
Stack Trace:
#0 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(98): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 14)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2016-09-14 06:42:15 Error: Fatal Error (4): syntax error, unexpected 'endforeach' (T_ENDFOREACH) in [C:\xampp\htdocs\cakephp\src\Template\Users\index.ctp, line 8]
Request URL: /cakephp/users/index
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 98
[main] - [internal], line ??



2016-09-14 06:42:15 Error: [Cake\Error\FatalErrorException] syntax error, unexpected 'endforeach' (T_ENDFOREACH)
Request URL: /cakephp/users/index
Stack Trace:
#0 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(98): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 8)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2016-09-14 15:05:53 Warning: Warning (2): Missing argument 1 for App\Controller\UsersController::view() in [C:\xampp\htdocs\cakephp\src\Controller\UsersController.php, line 17]
Request URL: /cakephp/users/view/
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 146
App\Controller\UsersController::view() - APP/Controller\UsersController.php, line 17
Cake\Controller\Controller::invokeAction() - CORE\src\Controller\Controller.php, line 435
Cake\Http\ActionDispatcher::_invoke() - CORE\src\Http\ActionDispatcher.php, line 122
Cake\Http\ActionDispatcher::dispatch() - CORE\src\Http\ActionDispatcher.php, line 96
Cake\Http\BaseApplication::__invoke() - CORE\src\Http\BaseApplication.php, line 83
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\RoutingMiddleware::__invoke() - CORE\src\Routing\Middleware\RoutingMiddleware.php, line 52
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\AssetMiddleware::__invoke() - CORE\src\Routing\Middleware\AssetMiddleware.php, line 88
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Error\Middleware\ErrorHandlerMiddleware::__invoke() - CORE\src\Error\Middleware\ErrorHandlerMiddleware.php, line 52
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Http\Runner::run() - CORE\src\Http\Runner.php, line 51
Cake\Http\Server::run() - CORE\src\Http\Server.php, line 82
[main] - ROOT\webroot\index.php, line 37



2016-09-18 06:01:29 Error: Fatal Error (1): Call to a member function newEntity() on null in [C:\xampp\htdocs\cakephp\src\Controller\UsersController.php, line 22]
Request URL: /cakephp/users/add
Referer URL: http://localhost/cakephp/users/index
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 98
[main] - [internal], line ??



2016-09-18 06:01:29 Warning: Headers already sent in C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Error\Debugger.php:753
2016-09-18 06:01:29 Error: [Cake\Error\FatalErrorException] Call to a member function newEntity() on null
Request URL: /cakephp/users/add
Referer URL: http://localhost/cakephp/users/index
Stack Trace:
#0 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(98): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 22)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2016-09-18 06:02:27 Error: Fatal Error (1): Call to a member function newEntity() on null in [C:\xampp\htdocs\cakephp\src\Controller\UsersController.php, line 22]
Request URL: /cakephp/users/add
Referer URL: http://localhost/cakephp/users/index
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 98
[main] - [internal], line ??



2016-09-18 06:02:27 Warning: Headers already sent in C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Error\Debugger.php:753
2016-09-18 06:02:27 Error: [Cake\Error\FatalErrorException] Call to a member function newEntity() on null
Request URL: /cakephp/users/add
Referer URL: http://localhost/cakephp/users/index
Stack Trace:
#0 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(98): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 22)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2016-09-18 06:03:13 Error: Fatal Error (1): Call to a member function newEntity() on boolean in [C:\xampp\htdocs\cakephp\src\Controller\UsersController.php, line 22]
Request URL: /cakephp/users/add
Referer URL: http://localhost/cakephp/users/index
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 98
[main] - [internal], line ??



2016-09-18 06:03:13 Error: [Cake\Error\FatalErrorException] Call to a member function newEntity() on boolean
Request URL: /cakephp/users/add
Referer URL: http://localhost/cakephp/users/index
Stack Trace:
#0 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(98): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 22)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2016-09-18 06:04:22 Error: Fatal Error (1): Call to undefined function App\Controller\set() in [C:\xampp\htdocs\cakephp\src\Controller\UsersController.php, line 23]
Request URL: /cakephp/users/add
Referer URL: http://localhost/cakephp/users/index
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 98
[main] - [internal], line ??



2016-09-18 06:04:22 Error: [Cake\Error\FatalErrorException] Call to undefined function App\Controller\set()
Request URL: /cakephp/users/add
Referer URL: http://localhost/cakephp/users/index
Stack Trace:
#0 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(98): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 23)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2016-09-18 06:04:24 Error: Fatal Error (1): Call to undefined function App\Controller\set() in [C:\xampp\htdocs\cakephp\src\Controller\UsersController.php, line 23]
Request URL: /cakephp/users/add
Referer URL: http://localhost/cakephp/users/index
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 98
[main] - [internal], line ??



2016-09-18 06:04:24 Error: [Cake\Error\FatalErrorException] Call to undefined function App\Controller\set()
Request URL: /cakephp/users/add
Referer URL: http://localhost/cakephp/users/index
Stack Trace:
#0 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(98): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 23)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2016-09-18 06:04:25 Error: Fatal Error (1): Call to undefined function App\Controller\set() in [C:\xampp\htdocs\cakephp\src\Controller\UsersController.php, line 23]
Request URL: /cakephp/users/add
Referer URL: http://localhost/cakephp/users/index
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 98
[main] - [internal], line ??



2016-09-18 06:04:25 Error: [Cake\Error\FatalErrorException] Call to undefined function App\Controller\set()
Request URL: /cakephp/users/add
Referer URL: http://localhost/cakephp/users/index
Stack Trace:
#0 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(98): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 23)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2016-09-18 06:04:43 Error: Fatal Error (1): Call to a member function newEntity() on boolean in [C:\xampp\htdocs\cakephp\src\Controller\UsersController.php, line 22]
Request URL: /cakephp/users/add
Referer URL: http://localhost/cakephp/users/index
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 98
[main] - [internal], line ??



2016-09-18 06:04:43 Error: [Cake\Error\FatalErrorException] Call to a member function newEntity() on boolean
Request URL: /cakephp/users/add
Referer URL: http://localhost/cakephp/users/index
Stack Trace:
#0 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(98): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 22)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2016-09-18 06:05:19 Error: Fatal Error (1): Call to undefined function App\Controller\set() in [C:\xampp\htdocs\cakephp\src\Controller\UsersController.php, line 23]
Request URL: /cakephp/users/add
Referer URL: http://localhost/cakephp/users/index
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 98
[main] - [internal], line ??



2016-09-18 06:05:19 Error: [Cake\Error\FatalErrorException] Call to undefined function App\Controller\set()
Request URL: /cakephp/users/add
Referer URL: http://localhost/cakephp/users/index
Stack Trace:
#0 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(98): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 23)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2016-09-18 06:07:09 Error: Fatal Error (4): syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ']' in [C:\xampp\htdocs\cakephp\src\Template\Users\add.ctp, line 8]
Request URL: /cakephp/users/add
Referer URL: http://localhost/cakephp/users/index
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 98
[main] - [internal], line ??



2016-09-18 06:07:09 Error: [Cake\Error\FatalErrorException] syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ']'
Request URL: /cakephp/users/add
Referer URL: http://localhost/cakephp/users/index
Stack Trace:
#0 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(98): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 8)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2016-09-18 06:15:07 Error: Fatal Error (4): syntax error, unexpected '}' in [C:\xampp\htdocs\cakephp\src\Controller\UsersController.php, line 26]
Request URL: /cakephp/users/add
Referer URL: http://localhost/cakephp/users/add
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 98
[main] - [internal], line ??



2016-09-18 06:15:07 Error: [Cake\Error\FatalErrorException] syntax error, unexpected '}'
Request URL: /cakephp/users/add
Referer URL: http://localhost/cakephp/users/add
Stack Trace:
#0 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(98): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 26)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2016-09-18 06:21:41 Error: Fatal Error (4): syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ']' in [C:\xampp\htdocs\cakephp\src\Controller\UsersController.php, line 29]
Request URL: /cakephp/users/add
Referer URL: http://localhost/cakephp/users/add
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 98
[main] - [internal], line ??



2016-09-18 06:21:42 Error: [Cake\Error\FatalErrorException] syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ']'
Request URL: /cakephp/users/add
Referer URL: http://localhost/cakephp/users/add
Stack Trace:
#0 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(98): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 29)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2016-09-18 06:25:07 Error: Fatal Error (1): Call to a member function newEntity() on boolean in [C:\xampp\htdocs\cakephp\src\Controller\UsersController.php, line 22]
Request URL: /cakephp/users/add
Referer URL: http://localhost/cakephp/users/add
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 98
[main] - [internal], line ??



2016-09-18 06:25:07 Error: [Cake\Error\FatalErrorException] Call to a member function newEntity() on boolean
Request URL: /cakephp/users/add
Referer URL: http://localhost/cakephp/users/add
Stack Trace:
#0 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(98): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 22)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2016-09-18 07:42:13 Error: Fatal Error (4): syntax error, unexpected ')', expecting ',' or ';' in [C:\xampp\htdocs\cakephp\src\Template\Users\add.ctp, line 17]
Request URL: /cakephp/users/add
Referer URL: http://localhost/cakephp/users/index
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 98
[main] - [internal], line ??



2016-09-18 07:42:13 Error: [Cake\Error\FatalErrorException] syntax error, unexpected ')', expecting ',' or ';'
Request URL: /cakephp/users/add
Referer URL: http://localhost/cakephp/users/index
Stack Trace:
#0 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(98): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 17)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2016-09-18 08:46:41 Error: Fatal Error (4): syntax error, unexpected '>' in [C:\xampp\htdocs\cakephp\src\Template\Layout\default.ctp, line 37]
Request URL: /cakephp/users/index
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 98
[main] - [internal], line ??



2016-09-18 08:46:41 Error: [Cake\Error\FatalErrorException] syntax error, unexpected '>'
Request URL: /cakephp/users/index
Stack Trace:
#0 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(98): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 37)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2016-09-18 08:46:41 Error: Fatal Error (4): syntax error, unexpected '>' in [C:\xampp\htdocs\cakephp\src\Template\Layout\default.ctp, line 37]
Request URL: /cakephp/users/index
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 98
[main] - [internal], line ??



2016-09-18 08:46:41 Error: [Cake\Error\FatalErrorException] syntax error, unexpected '>'
Request URL: /cakephp/users/index
Stack Trace:
#0 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(98): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 37)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2016-09-18 09:27:33 Error: Fatal Error (4): syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ']' in [C:\xampp\htdocs\cakephp\src\Controller\AppController.php, line 47]
Request URL: /cakephp/users/login
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 98
[main] - [internal], line ??



2016-09-18 09:27:33 Error: [Cake\Error\FatalErrorException] syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ']'
Request URL: /cakephp/users/login
Stack Trace:
#0 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(98): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 47)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2016-09-18 09:29:10 Error: Fatal Error (4): syntax error, unexpected ':' in [C:\xampp\htdocs\cakephp\src\Controller\AppController.php, line 69]
Request URL: /cakephp/users/login
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 98
[main] - [internal], line ??



2016-09-18 09:29:10 Error: [Cake\Error\FatalErrorException] syntax error, unexpected ':'
Request URL: /cakephp/users/login
Stack Trace:
#0 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(98): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 69)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2016-09-18 09:41:23 Error: Fatal Error (4): syntax error, unexpected '->' (T_OBJECT_OPERATOR), expecting ',' or ';' in [C:\xampp\htdocs\cakephp\src\Template\Users\login.ctp, line 13]
Request URL: /cakephp/users/login
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 98
[main] - [internal], line ??



2016-09-18 09:41:23 Error: [Cake\Error\FatalErrorException] syntax error, unexpected '->' (T_OBJECT_OPERATOR), expecting ',' or ';'
Request URL: /cakephp/users/login
Stack Trace:
#0 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(98): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 13)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2016-09-18 09:43:02 Error: Fatal Error (4): syntax error, unexpected 'class' (T_CLASS), expecting ']' in [C:\xampp\htdocs\cakephp\src\Template\Users\login.ctp, line 13]
Request URL: /cakephp/users/login
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 98
[main] - [internal], line ??



2016-09-18 09:43:02 Error: [Cake\Error\FatalErrorException] syntax error, unexpected 'class' (T_CLASS), expecting ']'
Request URL: /cakephp/users/login
Stack Trace:
#0 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(98): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 13)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2016-09-18 09:43:03 Error: Fatal Error (4): syntax error, unexpected 'class' (T_CLASS), expecting ']' in [C:\xampp\htdocs\cakephp\src\Template\Users\login.ctp, line 13]
Request URL: /cakephp/users/login
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 98
[main] - [internal], line ??



2016-09-18 09:43:03 Error: [Cake\Error\FatalErrorException] syntax error, unexpected 'class' (T_CLASS), expecting ']'
Request URL: /cakephp/users/login
Stack Trace:
#0 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(98): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 13)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2016-09-18 09:44:17 Error: Fatal Error (4): syntax error, unexpected '=', expecting ']' in [C:\xampp\htdocs\cakephp\src\Template\Users\login.ctp, line 13]
Request URL: /cakephp/users/login
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 98
[main] - [internal], line ??



2016-09-18 09:44:17 Error: [Cake\Error\FatalErrorException] syntax error, unexpected '=', expecting ']'
Request URL: /cakephp/users/login
Stack Trace:
#0 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(98): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 13)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2016-09-18 09:44:19 Error: Fatal Error (4): syntax error, unexpected '=', expecting ']' in [C:\xampp\htdocs\cakephp\src\Template\Users\login.ctp, line 13]
Request URL: /cakephp/users/login
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 98
[main] - [internal], line ??



2016-09-18 09:44:19 Error: [Cake\Error\FatalErrorException] syntax error, unexpected '=', expecting ']'
Request URL: /cakephp/users/login
Stack Trace:
#0 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(98): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 13)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2016-09-18 09:48:14 Error: Fatal Error (4): syntax error, unexpected '->' (T_OBJECT_OPERATOR), expecting ',' or ';' in [C:\xampp\htdocs\cakephp\src\Template\Users\login.ctp, line 24]
Request URL: /cakephp/users/login
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 98
[main] - [internal], line ??



2016-09-18 09:48:14 Error: [Cake\Error\FatalErrorException] syntax error, unexpected '->' (T_OBJECT_OPERATOR), expecting ',' or ';'
Request URL: /cakephp/users/login
Stack Trace:
#0 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(98): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 24)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2016-09-18 09:48:40 Error: Fatal Error (4): syntax error, unexpected '->' (T_OBJECT_OPERATOR), expecting ',' or ';' in [C:\xampp\htdocs\cakephp\src\Template\Users\login.ctp, line 24]
Request URL: /cakephp/users/login
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 98
[main] - [internal], line ??



2016-09-18 09:48:40 Error: [Cake\Error\FatalErrorException] syntax error, unexpected '->' (T_OBJECT_OPERATOR), expecting ',' or ';'
Request URL: /cakephp/users/login
Stack Trace:
#0 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(98): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 24)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2016-09-18 09:48:42 Error: Fatal Error (4): syntax error, unexpected '->' (T_OBJECT_OPERATOR), expecting ',' or ';' in [C:\xampp\htdocs\cakephp\src\Template\Users\login.ctp, line 24]
Request URL: /cakephp/users/login
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 98
[main] - [internal], line ??



2016-09-18 09:48:42 Error: [Cake\Error\FatalErrorException] syntax error, unexpected '->' (T_OBJECT_OPERATOR), expecting ',' or ';'
Request URL: /cakephp/users/login
Stack Trace:
#0 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(98): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 24)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2016-09-18 09:56:32 Error: Fatal Error (1): Call to a member function success() on boolean in [C:\xampp\htdocs\cakephp\src\Controller\UsersController.php, line 47]
Request URL: /cakephp/users/add
Referer URL: http://localhost/cakephp/users/add
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 98
[main] - [internal], line ??



2016-09-18 09:56:32 Error: [Cake\Error\FatalErrorException] Call to a member function success() on boolean
Request URL: /cakephp/users/add
Referer URL: http://localhost/cakephp/users/add
Stack Trace:
#0 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(98): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 47)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2016-09-18 09:56:56 Error: Fatal Error (1): Call to a member function error() on boolean in [C:\xampp\htdocs\cakephp\src\Controller\UsersController.php, line 51]
Request URL: /cakephp/users/add
Referer URL: http://localhost/cakephp/users/add
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 98
[main] - [internal], line ??



2016-09-18 09:56:56 Error: [Cake\Error\FatalErrorException] Call to a member function error() on boolean
Request URL: /cakephp/users/add
Referer URL: http://localhost/cakephp/users/add
Stack Trace:
#0 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(98): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2016-09-18 09:58:02 Error: Fatal Error (1): Call to a member function error() on boolean in [C:\xampp\htdocs\cakephp\src\Controller\UsersController.php, line 51]
Request URL: /cakephp/users/add
Referer URL: http://localhost/cakephp/users/add
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 98
[main] - [internal], line ??



2016-09-18 09:58:02 Error: [Cake\Error\FatalErrorException] Call to a member function error() on boolean
Request URL: /cakephp/users/add
Referer URL: http://localhost/cakephp/users/add
Stack Trace:
#0 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(98): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2016-09-18 09:58:20 Error: Fatal Error (1): Call to a member function error() on boolean in [C:\xampp\htdocs\cakephp\src\Controller\UsersController.php, line 51]
Request URL: /cakephp/users/add
Referer URL: http://localhost/cakephp/users/add
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 98
[main] - [internal], line ??



2016-09-18 09:58:20 Error: [Cake\Error\FatalErrorException] Call to a member function error() on boolean
Request URL: /cakephp/users/add
Referer URL: http://localhost/cakephp/users/add
Stack Trace:
#0 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(98): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2016-09-18 09:59:01 Error: Fatal Error (1): Call to a member function error() on boolean in [C:\xampp\htdocs\cakephp\src\Controller\UsersController.php, line 51]
Request URL: /cakephp/users/add
Referer URL: http://localhost/cakephp/users/add
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 98
[main] - [internal], line ??



2016-09-18 09:59:01 Error: [Cake\Error\FatalErrorException] Call to a member function error() on boolean
Request URL: /cakephp/users/add
Referer URL: http://localhost/cakephp/users/add
Stack Trace:
#0 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(98): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 51)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2016-09-18 09:59:53 Error: Fatal Error (1): Call to a member function success() on boolean in [C:\xampp\htdocs\cakephp\src\Controller\UsersController.php, line 47]
Request URL: /cakephp/users/add
Referer URL: http://localhost/cakephp/users/add
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 98
[main] - [internal], line ??



2016-09-18 09:59:53 Error: [Cake\Error\FatalErrorException] Call to a member function success() on boolean
Request URL: /cakephp/users/add
Referer URL: http://localhost/cakephp/users/add
Stack Trace:
#0 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(98): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 47)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2016-09-18 10:09:24 Warning: Warning (2): link() expects parameter 2 to be string, array given in [C:\xampp\htdocs\cakephp\src\Template\Element\menu.ctp, line 29]
Request URL: /cakephp/users/home
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 146
link - [internal], line ??
include - APP/Template\Element\menu.ctp, line 29
Cake\View\View::_evaluate() - CORE\src\View\View.php, line 1008
Cake\View\View::_render() - CORE\src\View\View.php, line 967
Cake\View\View::_renderElement() - CORE\src\View\View.php, line 1353
Cake\View\View::element() - CORE\src\View\View.php, line 496
include - APP/Template\Layout\default.ctp, line 37
Cake\View\View::_evaluate() - CORE\src\View\View.php, line 1008
Cake\View\View::_render() - CORE\src\View\View.php, line 967
Cake\View\View::renderLayout() - CORE\src\View\View.php, line 638
Cake\View\View::render() - CORE\src\View\View.php, line 596
Cake\Controller\Controller::render() - CORE\src\Controller\Controller.php, line 617
App\Controller\UsersController::home() - APP/Controller\UsersController.php, line 30
Cake\Controller\Controller::invokeAction() - CORE\src\Controller\Controller.php, line 435
Cake\Http\ActionDispatcher::_invoke() - CORE\src\Http\ActionDispatcher.php, line 122
Cake\Http\ActionDispatcher::dispatch() - CORE\src\Http\ActionDispatcher.php, line 96
Cake\Http\BaseApplication::__invoke() - CORE\src\Http\BaseApplication.php, line 83
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\RoutingMiddleware::__invoke() - CORE\src\Routing\Middleware\RoutingMiddleware.php, line 52
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\AssetMiddleware::__invoke() - CORE\src\Routing\Middleware\AssetMiddleware.php, line 88
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Error\Middleware\ErrorHandlerMiddleware::__invoke() - CORE\src\Error\Middleware\ErrorHandlerMiddleware.php, line 52
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Http\Runner::run() - CORE\src\Http\Runner.php, line 51
Cake\Http\Server::run() - CORE\src\Http\Server.php, line 82
[main] - ROOT\webroot\index.php, line 37



2016-09-18 10:12:07 Warning: Warning (2): link() expects parameter 2 to be string, array given in [C:\xampp\htdocs\cakephp\src\Template\Element\menu.ctp, line 29]
Request URL: /cakephp/users/home
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 146
link - [internal], line ??
include - APP/Template\Element\menu.ctp, line 29
Cake\View\View::_evaluate() - CORE\src\View\View.php, line 1008
Cake\View\View::_render() - CORE\src\View\View.php, line 967
Cake\View\View::_renderElement() - CORE\src\View\View.php, line 1353
Cake\View\View::element() - CORE\src\View\View.php, line 496
include - APP/Template\Layout\default.ctp, line 37
Cake\View\View::_evaluate() - CORE\src\View\View.php, line 1008
Cake\View\View::_render() - CORE\src\View\View.php, line 967
Cake\View\View::renderLayout() - CORE\src\View\View.php, line 638
Cake\View\View::render() - CORE\src\View\View.php, line 596
Cake\Controller\Controller::render() - CORE\src\Controller\Controller.php, line 617
App\Controller\UsersController::home() - APP/Controller\UsersController.php, line 30
Cake\Controller\Controller::invokeAction() - CORE\src\Controller\Controller.php, line 435
Cake\Http\ActionDispatcher::_invoke() - CORE\src\Http\ActionDispatcher.php, line 122
Cake\Http\ActionDispatcher::dispatch() - CORE\src\Http\ActionDispatcher.php, line 96
Cake\Http\BaseApplication::__invoke() - CORE\src\Http\BaseApplication.php, line 83
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\RoutingMiddleware::__invoke() - CORE\src\Routing\Middleware\RoutingMiddleware.php, line 52
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\AssetMiddleware::__invoke() - CORE\src\Routing\Middleware\AssetMiddleware.php, line 88
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Error\Middleware\ErrorHandlerMiddleware::__invoke() - CORE\src\Error\Middleware\ErrorHandlerMiddleware.php, line 52
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Http\Runner::run() - CORE\src\Http\Runner.php, line 51
Cake\Http\Server::run() - CORE\src\Http\Server.php, line 82
[main] - ROOT\webroot\index.php, line 37



2016-09-18 10:12:13 Warning: Warning (2): link() expects parameter 2 to be string, array given in [C:\xampp\htdocs\cakephp\src\Template\Element\menu.ctp, line 29]
Request URL: /cakephp/users/
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 146
link - [internal], line ??
include - APP/Template\Element\menu.ctp, line 29
Cake\View\View::_evaluate() - CORE\src\View\View.php, line 1008
Cake\View\View::_render() - CORE\src\View\View.php, line 967
Cake\View\View::_renderElement() - CORE\src\View\View.php, line 1353
Cake\View\View::element() - CORE\src\View\View.php, line 496
include - APP/Template\Layout\default.ctp, line 37
Cake\View\View::_evaluate() - CORE\src\View\View.php, line 1008
Cake\View\View::_render() - CORE\src\View\View.php, line 967
Cake\View\View::renderLayout() - CORE\src\View\View.php, line 638
Cake\View\View::render() - CORE\src\View\View.php, line 596
Cake\Controller\Controller::render() - CORE\src\Controller\Controller.php, line 617
Cake\Http\ActionDispatcher::_invoke() - CORE\src\Http\ActionDispatcher.php, line 128
Cake\Http\ActionDispatcher::dispatch() - CORE\src\Http\ActionDispatcher.php, line 96
Cake\Http\BaseApplication::__invoke() - CORE\src\Http\BaseApplication.php, line 83
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\RoutingMiddleware::__invoke() - CORE\src\Routing\Middleware\RoutingMiddleware.php, line 52
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\AssetMiddleware::__invoke() - CORE\src\Routing\Middleware\AssetMiddleware.php, line 88
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Error\Middleware\ErrorHandlerMiddleware::__invoke() - CORE\src\Error\Middleware\ErrorHandlerMiddleware.php, line 52
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Http\Runner::run() - CORE\src\Http\Runner.php, line 51
Cake\Http\Server::run() - CORE\src\Http\Server.php, line 82
[main] - ROOT\webroot\index.php, line 37



2016-09-18 10:13:54 Error: Fatal Error (1): Call to a member function error() on null in [C:\xampp\htdocs\cakephp\src\Controller\UsersController.php, line 24]
Request URL: /cakephp/users/login
Referer URL: http://localhost/cakephp/users/login
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 98
[main] - [internal], line ??



2016-09-18 10:13:54 Warning: Headers already sent in C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Error\Debugger.php:753
2016-09-18 10:13:54 Error: [Cake\Error\FatalErrorException] Call to a member function error() on null
Request URL: /cakephp/users/login
Referer URL: http://localhost/cakephp/users/login
Stack Trace:
#0 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(98): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 24)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2016-09-18 10:14:32 Error: Fatal Error (1): Call to a member function error() on null in [C:\xampp\htdocs\cakephp\src\Controller\UsersController.php, line 24]
Request URL: /cakephp/users/login
Referer URL: http://localhost/cakephp/users/login
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 98
[main] - [internal], line ??



2016-09-18 10:14:32 Warning: Headers already sent in C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Error\Debugger.php:753
2016-09-18 10:14:32 Error: [Cake\Error\FatalErrorException] Call to a member function error() on null
Request URL: /cakephp/users/login
Referer URL: http://localhost/cakephp/users/login
Stack Trace:
#0 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(98): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 24)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2016-09-18 10:21:26 Warning: Warning (2): Illegal string offset 'first_name' in [C:\xampp\htdocs\cakephp\src\Template\Users\home.ctp, line 1]
Request URL: /cakephp/users/home
Referer URL: http://localhost/cakephp/users/login
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 146
include - APP/Template\Users\home.ctp, line 1
Cake\View\View::_evaluate() - CORE\src\View\View.php, line 1008
Cake\View\View::_render() - CORE\src\View\View.php, line 967
Cake\View\View::render() - CORE\src\View\View.php, line 591
Cake\Controller\Controller::render() - CORE\src\Controller\Controller.php, line 617
App\Controller\UsersController::home() - APP/Controller\UsersController.php, line 30
Cake\Controller\Controller::invokeAction() - CORE\src\Controller\Controller.php, line 435
Cake\Http\ActionDispatcher::_invoke() - CORE\src\Http\ActionDispatcher.php, line 122
Cake\Http\ActionDispatcher::dispatch() - CORE\src\Http\ActionDispatcher.php, line 96
Cake\Http\BaseApplication::__invoke() - CORE\src\Http\BaseApplication.php, line 83
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\RoutingMiddleware::__invoke() - CORE\src\Routing\Middleware\RoutingMiddleware.php, line 52
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\AssetMiddleware::__invoke() - CORE\src\Routing\Middleware\AssetMiddleware.php, line 88
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Error\Middleware\ErrorHandlerMiddleware::__invoke() - CORE\src\Error\Middleware\ErrorHandlerMiddleware.php, line 52
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Http\Runner::run() - CORE\src\Http\Runner.php, line 51
Cake\Http\Server::run() - CORE\src\Http\Server.php, line 82
[main] - ROOT\webroot\index.php, line 37



2016-09-18 10:29:41 Error: Fatal Error (4): syntax error, unexpected '>' in [C:\xampp\htdocs\cakephp\src\Controller\AppController.php, line 54]
Request URL: /cakephp/users/login
Referer URL: http://localhost/cakephp/users/home
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 98
[main] - [internal], line ??



2016-09-18 10:29:41 Error: [Cake\Error\FatalErrorException] syntax error, unexpected '>'
Request URL: /cakephp/users/login
Referer URL: http://localhost/cakephp/users/home
Stack Trace:
#0 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(98): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 54)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2016-09-18 10:30:13 Error: Fatal Error (4): syntax error, unexpected ':' in [C:\xampp\htdocs\cakephp\src\Model\Table\UsersTable.php, line 107]
Request URL: /cakephp/users/login
Referer URL: http://localhost/cakephp/users/login
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 98
[main] - [internal], line ??



2016-09-18 10:30:13 Error: [Cake\Error\FatalErrorException] syntax error, unexpected ':'
Request URL: /cakephp/users/login
Referer URL: http://localhost/cakephp/users/login
Stack Trace:
#0 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(98): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 107)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2016-09-18 10:58:14 Error: Fatal Error (4): syntax error, unexpected 'and' (T_LOGICAL_AND) in [C:\xampp\htdocs\cakephp\src\Controller\UsersController.php, line 15]
Request URL: /cakephp/users/login
Referer URL: http://localhost/cakephp/users/home
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 98
[main] - [internal], line ??



2016-09-18 10:58:14 Error: [Cake\Error\FatalErrorException] syntax error, unexpected 'and' (T_LOGICAL_AND)
Request URL: /cakephp/users/login
Referer URL: http://localhost/cakephp/users/home
Stack Trace:
#0 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(98): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 15)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2016-09-18 10:58:21 Error: Fatal Error (4): syntax error, unexpected 'and' (T_LOGICAL_AND) in [C:\xampp\htdocs\cakephp\src\Controller\UsersController.php, line 15]
Request URL: /cakephp/users/home
Referer URL: http://localhost/cakephp/users/login
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 98
[main] - [internal], line ??



2016-09-18 10:58:21 Error: [Cake\Error\FatalErrorException] syntax error, unexpected 'and' (T_LOGICAL_AND)
Request URL: /cakephp/users/home
Referer URL: http://localhost/cakephp/users/login
Stack Trace:
#0 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(98): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 15)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2016-09-18 10:58:22 Error: Fatal Error (4): syntax error, unexpected 'and' (T_LOGICAL_AND) in [C:\xampp\htdocs\cakephp\src\Controller\UsersController.php, line 15]
Request URL: /cakephp/users/login
Referer URL: http://localhost/cakephp/users/
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 98
[main] - [internal], line ??



2016-09-18 10:58:22 Error: [Cake\Error\FatalErrorException] syntax error, unexpected 'and' (T_LOGICAL_AND)
Request URL: /cakephp/users/login
Referer URL: http://localhost/cakephp/users/
Stack Trace:
#0 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(98): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 15)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2016-09-18 10:58:23 Error: Fatal Error (4): syntax error, unexpected 'and' (T_LOGICAL_AND) in [C:\xampp\htdocs\cakephp\src\Controller\UsersController.php, line 15]
Request URL: /cakephp/users/
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 98
[main] - [internal], line ??



2016-09-18 10:58:23 Error: [Cake\Error\FatalErrorException] syntax error, unexpected 'and' (T_LOGICAL_AND)
Request URL: /cakephp/users/
Stack Trace:
#0 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(98): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 15)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2016-09-18 10:58:30 Error: Fatal Error (4): syntax error, unexpected 'and' (T_LOGICAL_AND) in [C:\xampp\htdocs\cakephp\src\Controller\UsersController.php, line 15]
Request URL: /cakephp/users/
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 98
[main] - [internal], line ??



2016-09-18 10:58:30 Error: [Cake\Error\FatalErrorException] syntax error, unexpected 'and' (T_LOGICAL_AND)
Request URL: /cakephp/users/
Stack Trace:
#0 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(98): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 15)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2016-09-18 10:58:33 Error: Fatal Error (4): syntax error, unexpected 'and' (T_LOGICAL_AND) in [C:\xampp\htdocs\cakephp\src\Controller\UsersController.php, line 15]
Request URL: /cakephp/users/
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 98
[main] - [internal], line ??



2016-09-18 10:58:33 Error: [Cake\Error\FatalErrorException] syntax error, unexpected 'and' (T_LOGICAL_AND)
Request URL: /cakephp/users/
Stack Trace:
#0 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(98): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 15)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2016-09-18 10:59:04 Error: Fatal Error (4): syntax error, unexpected ''unauthorizedRedirect'' (T_CONSTANT_ENCAPSED_STRING), expecting ']' in [C:\xampp\htdocs\cakephp\src\Controller\AppController.php, line 70]
Request URL: /cakephp/users/
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 98
[main] - [internal], line ??



2016-09-18 10:59:04 Error: [Cake\Error\FatalErrorException] syntax error, unexpected ''unauthorizedRedirect'' (T_CONSTANT_ENCAPSED_STRING), expecting ']'
Request URL: /cakephp/users/
Stack Trace:
#0 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(98): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 70)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2016-09-18 11:00:12 Error: Fatal Error (4): syntax error, unexpected ';', expecting ']' in [C:\xampp\htdocs\cakephp\src\Controller\AppController.php, line 70]
Request URL: /cakephp/users/
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 98
[main] - [internal], line ??



2016-09-18 11:00:12 Error: [Cake\Error\FatalErrorException] syntax error, unexpected ';', expecting ']'
Request URL: /cakephp/users/
Stack Trace:
#0 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(98): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 70)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2016-09-18 11:00:29 Error: Fatal Error (1): Call to undefined method App\Controller\UsersController::reference() in [C:\xampp\htdocs\cakephp\src\Controller\AppController.php, line 70]
Request URL: /cakephp/users/
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 98
[main] - [internal], line ??



2016-09-18 11:00:29 Error: [Cake\Error\FatalErrorException] Call to undefined method App\Controller\UsersController::reference()
Request URL: /cakephp/users/
Stack Trace:
#0 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(98): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 70)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2016-09-18 18:39:51 Error: Fatal Error (4): syntax error, unexpected ':' in [C:\xampp\htdocs\cakephp\src\Controller\UsersController.php, line 52]
Request URL: /cakephp/users/
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 98
[main] - [internal], line ??



2016-09-18 18:39:53 Error: [Cake\Error\FatalErrorException] syntax error, unexpected ':'
Request URL: /cakephp/users/
Stack Trace:
#0 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(98): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 52)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2016-09-18 20:30:44 Error: Fatal Error (1): Call to undefined method App\View\AppView::link() in [C:\xampp\htdocs\cakephp\src\Template\Users\home.ctp, line 1]
Request URL: /cakephp/users/home
Referer URL: http://localhost/cakephp/users/login
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 98
[main] - [internal], line ??



2016-09-18 20:30:44 Error: [Cake\Error\FatalErrorException] Call to undefined method App\View\AppView::link()
Request URL: /cakephp/users/home
Referer URL: http://localhost/cakephp/users/login
Stack Trace:
#0 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(98): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 1)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2016-09-18 20:35:25 Error: Fatal Error (1): Call to undefined method App\View\AppView::link() in [C:\xampp\htdocs\cakephp\src\Template\Users\home.ctp, line 1]
Request URL: /cakephp/users/home
Referer URL: http://localhost/cakephp/users/login
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 98
[main] - [internal], line ??



2016-09-18 20:35:25 Error: [Cake\Error\FatalErrorException] Call to undefined method App\View\AppView::link()
Request URL: /cakephp/users/home
Referer URL: http://localhost/cakephp/users/login
Stack Trace:
#0 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(98): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 1)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2016-09-18 20:35:25 Error: Fatal Error (1): Call to undefined method App\View\AppView::link() in [C:\xampp\htdocs\cakephp\src\Template\Users\home.ctp, line 1]
Request URL: /cakephp/users/home
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 98
[main] - [internal], line ??



2016-09-18 20:35:25 Error: [Cake\Error\FatalErrorException] Call to undefined method App\View\AppView::link()
Request URL: /cakephp/users/home
Stack Trace:
#0 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(98): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 1)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2016-09-18 20:35:30 Error: Fatal Error (1): Call to undefined method App\View\AppView::link() in [C:\xampp\htdocs\cakephp\src\Template\Users\home.ctp, line 1]
Request URL: /cakephp/users/home
Referer URL: http://localhost/cakephp/users/login
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 98
[main] - [internal], line ??



2016-09-18 20:35:30 Error: [Cake\Error\FatalErrorException] Call to undefined method App\View\AppView::link()
Request URL: /cakephp/users/home
Referer URL: http://localhost/cakephp/users/login
Stack Trace:
#0 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(98): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 1)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2016-09-18 20:35:44 Error: Fatal Error (1): Call to undefined method App\View\AppView::link() in [C:\xampp\htdocs\cakephp\src\Template\Users\home.ctp, line 1]
Request URL: /cakephp/users/home
Referer URL: http://localhost/cakephp/users/login
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 98
[main] - [internal], line ??



2016-09-18 20:35:44 Error: [Cake\Error\FatalErrorException] Call to undefined method App\View\AppView::link()
Request URL: /cakephp/users/home
Referer URL: http://localhost/cakephp/users/login
Stack Trace:
#0 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(98): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 1)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2016-09-18 20:36:41 Error: Fatal Error (1): Call to undefined method App\View\AppView::link() in [C:\xampp\htdocs\cakephp\src\Template\Users\home.ctp, line 1]
Request URL: /cakephp/users/home
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 98
[main] - [internal], line ??



2016-09-18 20:36:41 Error: [Cake\Error\FatalErrorException] Call to undefined method App\View\AppView::link()
Request URL: /cakephp/users/home
Stack Trace:
#0 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(98): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 1)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2016-09-18 20:36:56 Error: Fatal Error (1): Call to undefined method App\View\AppView::link() in [C:\xampp\htdocs\cakephp\src\Template\Users\home.ctp, line 1]
Request URL: /cakephp/users/home
Referer URL: http://localhost/cakephp/users/login
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 98
[main] - [internal], line ??



2016-09-18 20:36:56 Error: [Cake\Error\FatalErrorException] Call to undefined method App\View\AppView::link()
Request URL: /cakephp/users/home
Referer URL: http://localhost/cakephp/users/login
Stack Trace:
#0 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(98): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 1)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2016-09-18 22:49:59 Error: Fatal Error (4): syntax error, unexpected ',' in [C:\xampp\htdocs\cakephp\src\Template\Users\index.ctp, line 27]
Request URL: /cakephp/users/index
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 98
[main] - [internal], line ??



2016-09-18 22:49:59 Error: [Cake\Error\FatalErrorException] syntax error, unexpected ','
Request URL: /cakephp/users/index
Stack Trace:
#0 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(98): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 27)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2016-10-06 02:44:10 Warning: Warning (2): scandir(images/capturas/The Witcher 3,images/capturas/The Witcher 3): El sistema no puede encontrar la ruta especificada. (code: 3) in [C:\xampp\htdocs\cakephp\src\Template\Users\login.ctp, line 189]
Request URL: /cakephp/
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 146
scandir - [internal], line ??
include - APP/Template\Users\login.ctp, line 189
Cake\View\View::_evaluate() - CORE\src\View\View.php, line 1008
Cake\View\View::_render() - CORE\src\View\View.php, line 967
Cake\View\View::render() - CORE\src\View\View.php, line 591
Cake\Controller\Controller::render() - CORE\src\Controller\Controller.php, line 617
Cake\Http\ActionDispatcher::_invoke() - CORE\src\Http\ActionDispatcher.php, line 128
Cake\Http\ActionDispatcher::dispatch() - CORE\src\Http\ActionDispatcher.php, line 96
Cake\Http\BaseApplication::__invoke() - CORE\src\Http\BaseApplication.php, line 83
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\RoutingMiddleware::__invoke() - CORE\src\Routing\Middleware\RoutingMiddleware.php, line 52
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\AssetMiddleware::__invoke() - CORE\src\Routing\Middleware\AssetMiddleware.php, line 88
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Error\Middleware\ErrorHandlerMiddleware::__invoke() - CORE\src\Error\Middleware\ErrorHandlerMiddleware.php, line 52
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Http\Runner::run() - CORE\src\Http\Runner.php, line 51
Cake\Http\Server::run() - CORE\src\Http\Server.php, line 82
[main] - ROOT\webroot\index.php, line 37



2016-10-06 02:44:10 Warning: Warning (2): scandir(images/capturas/The Witcher 3) [<a href='http://php.net/function.scandir'>function.scandir</a>]: failed to open dir: No such file or directory in [C:\xampp\htdocs\cakephp\src\Template\Users\login.ctp, line 189]
Request URL: /cakephp/
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 146
scandir - [internal], line ??
include - APP/Template\Users\login.ctp, line 189
Cake\View\View::_evaluate() - CORE\src\View\View.php, line 1008
Cake\View\View::_render() - CORE\src\View\View.php, line 967
Cake\View\View::render() - CORE\src\View\View.php, line 591
Cake\Controller\Controller::render() - CORE\src\Controller\Controller.php, line 617
Cake\Http\ActionDispatcher::_invoke() - CORE\src\Http\ActionDispatcher.php, line 128
Cake\Http\ActionDispatcher::dispatch() - CORE\src\Http\ActionDispatcher.php, line 96
Cake\Http\BaseApplication::__invoke() - CORE\src\Http\BaseApplication.php, line 83
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\RoutingMiddleware::__invoke() - CORE\src\Routing\Middleware\RoutingMiddleware.php, line 52
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\AssetMiddleware::__invoke() - CORE\src\Routing\Middleware\AssetMiddleware.php, line 88
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Error\Middleware\ErrorHandlerMiddleware::__invoke() - CORE\src\Error\Middleware\ErrorHandlerMiddleware.php, line 52
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Http\Runner::run() - CORE\src\Http\Runner.php, line 51
Cake\Http\Server::run() - CORE\src\Http\Server.php, line 82
[main] - ROOT\webroot\index.php, line 37



2016-10-06 02:44:10 Warning: Warning (2): scandir() [<a href='http://php.net/function.scandir'>function.scandir</a>]: (errno 2): No such file or directory in [C:\xampp\htdocs\cakephp\src\Template\Users\login.ctp, line 189]
Request URL: /cakephp/
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 146
scandir - [internal], line ??
include - APP/Template\Users\login.ctp, line 189
Cake\View\View::_evaluate() - CORE\src\View\View.php, line 1008
Cake\View\View::_render() - CORE\src\View\View.php, line 967
Cake\View\View::render() - CORE\src\View\View.php, line 591
Cake\Controller\Controller::render() - CORE\src\Controller\Controller.php, line 617
Cake\Http\ActionDispatcher::_invoke() - CORE\src\Http\ActionDispatcher.php, line 128
Cake\Http\ActionDispatcher::dispatch() - CORE\src\Http\ActionDispatcher.php, line 96
Cake\Http\BaseApplication::__invoke() - CORE\src\Http\BaseApplication.php, line 83
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\RoutingMiddleware::__invoke() - CORE\src\Routing\Middleware\RoutingMiddleware.php, line 52
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\AssetMiddleware::__invoke() - CORE\src\Routing\Middleware\AssetMiddleware.php, line 88
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Error\Middleware\ErrorHandlerMiddleware::__invoke() - CORE\src\Error\Middleware\ErrorHandlerMiddleware.php, line 52
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Http\Runner::run() - CORE\src\Http\Runner.php, line 51
Cake\Http\Server::run() - CORE\src\Http\Server.php, line 82
[main] - ROOT\webroot\index.php, line 37



2016-10-06 02:44:10 Warning: Warning (2): array_diff() [<a href='http://php.net/function.array-diff'>function.array-diff</a>]: Argument #1 is not an array in [C:\xampp\htdocs\cakephp\src\Template\Users\login.ctp, line 189]
Request URL: /cakephp/
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 146
array_diff - [internal], line ??
include - APP/Template\Users\login.ctp, line 189
Cake\View\View::_evaluate() - CORE\src\View\View.php, line 1008
Cake\View\View::_render() - CORE\src\View\View.php, line 967
Cake\View\View::render() - CORE\src\View\View.php, line 591
Cake\Controller\Controller::render() - CORE\src\Controller\Controller.php, line 617
Cake\Http\ActionDispatcher::_invoke() - CORE\src\Http\ActionDispatcher.php, line 128
Cake\Http\ActionDispatcher::dispatch() - CORE\src\Http\ActionDispatcher.php, line 96
Cake\Http\BaseApplication::__invoke() - CORE\src\Http\BaseApplication.php, line 83
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\RoutingMiddleware::__invoke() - CORE\src\Routing\Middleware\RoutingMiddleware.php, line 52
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\AssetMiddleware::__invoke() - CORE\src\Routing\Middleware\AssetMiddleware.php, line 88
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Error\Middleware\ErrorHandlerMiddleware::__invoke() - CORE\src\Error\Middleware\ErrorHandlerMiddleware.php, line 52
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Http\Runner::run() - CORE\src\Http\Runner.php, line 51
Cake\Http\Server::run() - CORE\src\Http\Server.php, line 82
[main] - ROOT\webroot\index.php, line 37



2016-10-05 21:29:34 Warning: Warning (2): scandir(images/capturas/The Witcher 3): failed to open dir: No such file or directory in [/home/satori/Documents/cakephp/src/Template/Users/login.ctp, line 189]
Request URL: /
Client IP: 127.0.0.1
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE/src/Error/BaseErrorHandler.php, line 146
scandir - [internal], line ??
include - APP/Template/Users/login.ctp, line 189
Cake\View\View::_evaluate() - CORE/src/View/View.php, line 1008
Cake\View\View::_render() - CORE/src/View/View.php, line 967
Cake\View\View::render() - CORE/src/View/View.php, line 591
Cake\Controller\Controller::render() - CORE/src/Controller/Controller.php, line 617
Cake\Http\ActionDispatcher::_invoke() - CORE/src/Http/ActionDispatcher.php, line 128
Cake\Http\ActionDispatcher::dispatch() - CORE/src/Http/ActionDispatcher.php, line 96
Cake\Http\BaseApplication::__invoke() - CORE/src/Http/BaseApplication.php, line 83
Cake\Http\Runner::__invoke() - CORE/src/Http/Runner.php, line 65
Cake\Routing\Middleware\RoutingMiddleware::__invoke() - CORE/src/Routing/Middleware/RoutingMiddleware.php, line 52
Cake\Http\Runner::__invoke() - CORE/src/Http/Runner.php, line 65
Cake\Routing\Middleware\AssetMiddleware::__invoke() - CORE/src/Routing/Middleware/AssetMiddleware.php, line 88
Cake\Http\Runner::__invoke() - CORE/src/Http/Runner.php, line 65
Cake\Error\Middleware\ErrorHandlerMiddleware::__invoke() - CORE/src/Error/Middleware/ErrorHandlerMiddleware.php, line 52
Cake\Http\Runner::__invoke() - CORE/src/Http/Runner.php, line 65
Cake\Http\Runner::run() - CORE/src/Http/Runner.php, line 51
Cake\Http\Server::run() - CORE/src/Http/Server.php, line 82
[main] - ROOT/webroot/index.php, line 37



2016-10-05 21:29:34 Warning: Warning (2): scandir() [<a href='http://php.net/function.scandir'>function.scandir</a>]: (errno 0): Success in [/home/satori/Documents/cakephp/src/Template/Users/login.ctp, line 189]
Request URL: /
Client IP: 127.0.0.1
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE/src/Error/BaseErrorHandler.php, line 146
scandir - [internal], line ??
include - APP/Template/Users/login.ctp, line 189
Cake\View\View::_evaluate() - CORE/src/View/View.php, line 1008
Cake\View\View::_render() - CORE/src/View/View.php, line 967
Cake\View\View::render() - CORE/src/View/View.php, line 591
Cake\Controller\Controller::render() - CORE/src/Controller/Controller.php, line 617
Cake\Http\ActionDispatcher::_invoke() - CORE/src/Http/ActionDispatcher.php, line 128
Cake\Http\ActionDispatcher::dispatch() - CORE/src/Http/ActionDispatcher.php, line 96
Cake\Http\BaseApplication::__invoke() - CORE/src/Http/BaseApplication.php, line 83
Cake\Http\Runner::__invoke() - CORE/src/Http/Runner.php, line 65
Cake\Routing\Middleware\RoutingMiddleware::__invoke() - CORE/src/Routing/Middleware/RoutingMiddleware.php, line 52
Cake\Http\Runner::__invoke() - CORE/src/Http/Runner.php, line 65
Cake\Routing\Middleware\AssetMiddleware::__invoke() - CORE/src/Routing/Middleware/AssetMiddleware.php, line 88
Cake\Http\Runner::__invoke() - CORE/src/Http/Runner.php, line 65
Cake\Error\Middleware\ErrorHandlerMiddleware::__invoke() - CORE/src/Error/Middleware/ErrorHandlerMiddleware.php, line 52
Cake\Http\Runner::__invoke() - CORE/src/Http/Runner.php, line 65
Cake\Http\Runner::run() - CORE/src/Http/Runner.php, line 51
Cake\Http\Server::run() - CORE/src/Http/Server.php, line 82
[main] - ROOT/webroot/index.php, line 37



2016-10-05 21:29:34 Warning: Warning (2): array_diff() [<a href='http://php.net/function.array-diff'>function.array-diff</a>]: Argument #1 is not an array in [/home/satori/Documents/cakephp/src/Template/Users/login.ctp, line 189]
Request URL: /
Client IP: 127.0.0.1
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE/src/Error/BaseErrorHandler.php, line 146
array_diff - [internal], line ??
include - APP/Template/Users/login.ctp, line 189
Cake\View\View::_evaluate() - CORE/src/View/View.php, line 1008
Cake\View\View::_render() - CORE/src/View/View.php, line 967
Cake\View\View::render() - CORE/src/View/View.php, line 591
Cake\Controller\Controller::render() - CORE/src/Controller/Controller.php, line 617
Cake\Http\ActionDispatcher::_invoke() - CORE/src/Http/ActionDispatcher.php, line 128
Cake\Http\ActionDispatcher::dispatch() - CORE/src/Http/ActionDispatcher.php, line 96
Cake\Http\BaseApplication::__invoke() - CORE/src/Http/BaseApplication.php, line 83
Cake\Http\Runner::__invoke() - CORE/src/Http/Runner.php, line 65
Cake\Routing\Middleware\RoutingMiddleware::__invoke() - CORE/src/Routing/Middleware/RoutingMiddleware.php, line 52
Cake\Http\Runner::__invoke() - CORE/src/Http/Runner.php, line 65
Cake\Routing\Middleware\AssetMiddleware::__invoke() - CORE/src/Routing/Middleware/AssetMiddleware.php, line 88
Cake\Http\Runner::__invoke() - CORE/src/Http/Runner.php, line 65
Cake\Error\Middleware\ErrorHandlerMiddleware::__invoke() - CORE/src/Error/Middleware/ErrorHandlerMiddleware.php, line 52
Cake\Http\Runner::__invoke() - CORE/src/Http/Runner.php, line 65
Cake\Http\Runner::run() - CORE/src/Http/Runner.php, line 51
Cake\Http\Server::run() - CORE/src/Http/Server.php, line 82
[main] - ROOT/webroot/index.php, line 37



2016-10-05 22:38:52 Warning: Warning (2): scandir(images/capturas/The Witcher 3): failed to open dir: No such file or directory in [/home/satori/Documents/cakephp/src/Template/Users/login.ctp, line 189]
Request URL: /
Client IP: 127.0.0.1
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE/src/Error/BaseErrorHandler.php, line 146
scandir - [internal], line ??
include - APP/Template/Users/login.ctp, line 189
Cake\View\View::_evaluate() - CORE/src/View/View.php, line 1008
Cake\View\View::_render() - CORE/src/View/View.php, line 967
Cake\View\View::render() - CORE/src/View/View.php, line 591
Cake\Controller\Controller::render() - CORE/src/Controller/Controller.php, line 617
Cake\Http\ActionDispatcher::_invoke() - CORE/src/Http/ActionDispatcher.php, line 128
Cake\Http\ActionDispatcher::dispatch() - CORE/src/Http/ActionDispatcher.php, line 96
Cake\Http\BaseApplication::__invoke() - CORE/src/Http/BaseApplication.php, line 83
Cake\Http\Runner::__invoke() - CORE/src/Http/Runner.php, line 65
Cake\Routing\Middleware\RoutingMiddleware::__invoke() - CORE/src/Routing/Middleware/RoutingMiddleware.php, line 52
Cake\Http\Runner::__invoke() - CORE/src/Http/Runner.php, line 65
Cake\Routing\Middleware\AssetMiddleware::__invoke() - CORE/src/Routing/Middleware/AssetMiddleware.php, line 88
Cake\Http\Runner::__invoke() - CORE/src/Http/Runner.php, line 65
Cake\Error\Middleware\ErrorHandlerMiddleware::__invoke() - CORE/src/Error/Middleware/ErrorHandlerMiddleware.php, line 52
Cake\Http\Runner::__invoke() - CORE/src/Http/Runner.php, line 65
Cake\Http\Runner::run() - CORE/src/Http/Runner.php, line 51
Cake\Http\Server::run() - CORE/src/Http/Server.php, line 82
[main] - ROOT/webroot/index.php, line 37



2016-10-05 22:38:52 Warning: Warning (2): scandir() [<a href='http://php.net/function.scandir'>function.scandir</a>]: (errno 0): Success in [/home/satori/Documents/cakephp/src/Template/Users/login.ctp, line 189]
Request URL: /
Client IP: 127.0.0.1
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE/src/Error/BaseErrorHandler.php, line 146
scandir - [internal], line ??
include - APP/Template/Users/login.ctp, line 189
Cake\View\View::_evaluate() - CORE/src/View/View.php, line 1008
Cake\View\View::_render() - CORE/src/View/View.php, line 967
Cake\View\View::render() - CORE/src/View/View.php, line 591
Cake\Controller\Controller::render() - CORE/src/Controller/Controller.php, line 617
Cake\Http\ActionDispatcher::_invoke() - CORE/src/Http/ActionDispatcher.php, line 128
Cake\Http\ActionDispatcher::dispatch() - CORE/src/Http/ActionDispatcher.php, line 96
Cake\Http\BaseApplication::__invoke() - CORE/src/Http/BaseApplication.php, line 83
Cake\Http\Runner::__invoke() - CORE/src/Http/Runner.php, line 65
Cake\Routing\Middleware\RoutingMiddleware::__invoke() - CORE/src/Routing/Middleware/RoutingMiddleware.php, line 52
Cake\Http\Runner::__invoke() - CORE/src/Http/Runner.php, line 65
Cake\Routing\Middleware\AssetMiddleware::__invoke() - CORE/src/Routing/Middleware/AssetMiddleware.php, line 88
Cake\Http\Runner::__invoke() - CORE/src/Http/Runner.php, line 65
Cake\Error\Middleware\ErrorHandlerMiddleware::__invoke() - CORE/src/Error/Middleware/ErrorHandlerMiddleware.php, line 52
Cake\Http\Runner::__invoke() - CORE/src/Http/Runner.php, line 65
Cake\Http\Runner::run() - CORE/src/Http/Runner.php, line 51
Cake\Http\Server::run() - CORE/src/Http/Server.php, line 82
[main] - ROOT/webroot/index.php, line 37



2016-10-05 22:38:52 Warning: Warning (2): array_diff() [<a href='http://php.net/function.array-diff'>function.array-diff</a>]: Argument #1 is not an array in [/home/satori/Documents/cakephp/src/Template/Users/login.ctp, line 189]
Request URL: /
Client IP: 127.0.0.1
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE/src/Error/BaseErrorHandler.php, line 146
array_diff - [internal], line ??
include - APP/Template/Users/login.ctp, line 189
Cake\View\View::_evaluate() - CORE/src/View/View.php, line 1008
Cake\View\View::_render() - CORE/src/View/View.php, line 967
Cake\View\View::render() - CORE/src/View/View.php, line 591
Cake\Controller\Controller::render() - CORE/src/Controller/Controller.php, line 617
Cake\Http\ActionDispatcher::_invoke() - CORE/src/Http/ActionDispatcher.php, line 128
Cake\Http\ActionDispatcher::dispatch() - CORE/src/Http/ActionDispatcher.php, line 96
Cake\Http\BaseApplication::__invoke() - CORE/src/Http/BaseApplication.php, line 83
Cake\Http\Runner::__invoke() - CORE/src/Http/Runner.php, line 65
Cake\Routing\Middleware\RoutingMiddleware::__invoke() - CORE/src/Routing/Middleware/RoutingMiddleware.php, line 52
Cake\Http\Runner::__invoke() - CORE/src/Http/Runner.php, line 65
Cake\Routing\Middleware\AssetMiddleware::__invoke() - CORE/src/Routing/Middleware/AssetMiddleware.php, line 88
Cake\Http\Runner::__invoke() - CORE/src/Http/Runner.php, line 65
Cake\Error\Middleware\ErrorHandlerMiddleware::__invoke() - CORE/src/Error/Middleware/ErrorHandlerMiddleware.php, line 52
Cake\Http\Runner::__invoke() - CORE/src/Http/Runner.php, line 65
Cake\Http\Runner::run() - CORE/src/Http/Runner.php, line 51
Cake\Http\Server::run() - CORE/src/Http/Server.php, line 82
[main] - ROOT/webroot/index.php, line 37



2016-10-06 00:23:24 Warning: Warning (2): scandir(images/capturas/The Witcher 3): failed to open dir: No such file or directory in [/home/satori/Documents/cakephp/src/Template/Productos/login.ctp, line 189]
Request URL: /
Client IP: 127.0.0.1
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE/src/Error/BaseErrorHandler.php, line 146
scandir - [internal], line ??
include - APP/Template/Productos/login.ctp, line 189
Cake\View\View::_evaluate() - CORE/src/View/View.php, line 1008
Cake\View\View::_render() - CORE/src/View/View.php, line 967
Cake\View\View::render() - CORE/src/View/View.php, line 591
Cake\Controller\Controller::render() - CORE/src/Controller/Controller.php, line 617
Cake\Http\ActionDispatcher::_invoke() - CORE/src/Http/ActionDispatcher.php, line 128
Cake\Http\ActionDispatcher::dispatch() - CORE/src/Http/ActionDispatcher.php, line 96
Cake\Http\BaseApplication::__invoke() - CORE/src/Http/BaseApplication.php, line 83
Cake\Http\Runner::__invoke() - CORE/src/Http/Runner.php, line 65
Cake\Routing\Middleware\RoutingMiddleware::__invoke() - CORE/src/Routing/Middleware/RoutingMiddleware.php, line 52
Cake\Http\Runner::__invoke() - CORE/src/Http/Runner.php, line 65
Cake\Routing\Middleware\AssetMiddleware::__invoke() - CORE/src/Routing/Middleware/AssetMiddleware.php, line 88
Cake\Http\Runner::__invoke() - CORE/src/Http/Runner.php, line 65
Cake\Error\Middleware\ErrorHandlerMiddleware::__invoke() - CORE/src/Error/Middleware/ErrorHandlerMiddleware.php, line 52
Cake\Http\Runner::__invoke() - CORE/src/Http/Runner.php, line 65
Cake\Http\Runner::run() - CORE/src/Http/Runner.php, line 51
Cake\Http\Server::run() - CORE/src/Http/Server.php, line 82
[main] - ROOT/webroot/index.php, line 37



2016-10-06 00:23:24 Warning: Warning (2): scandir() [<a href='http://php.net/function.scandir'>function.scandir</a>]: (errno 0): Success in [/home/satori/Documents/cakephp/src/Template/Productos/login.ctp, line 189]
Request URL: /
Client IP: 127.0.0.1
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE/src/Error/BaseErrorHandler.php, line 146
scandir - [internal], line ??
include - APP/Template/Productos/login.ctp, line 189
Cake\View\View::_evaluate() - CORE/src/View/View.php, line 1008
Cake\View\View::_render() - CORE/src/View/View.php, line 967
Cake\View\View::render() - CORE/src/View/View.php, line 591
Cake\Controller\Controller::render() - CORE/src/Controller/Controller.php, line 617
Cake\Http\ActionDispatcher::_invoke() - CORE/src/Http/ActionDispatcher.php, line 128
Cake\Http\ActionDispatcher::dispatch() - CORE/src/Http/ActionDispatcher.php, line 96
Cake\Http\BaseApplication::__invoke() - CORE/src/Http/BaseApplication.php, line 83
Cake\Http\Runner::__invoke() - CORE/src/Http/Runner.php, line 65
Cake\Routing\Middleware\RoutingMiddleware::__invoke() - CORE/src/Routing/Middleware/RoutingMiddleware.php, line 52
Cake\Http\Runner::__invoke() - CORE/src/Http/Runner.php, line 65
Cake\Routing\Middleware\AssetMiddleware::__invoke() - CORE/src/Routing/Middleware/AssetMiddleware.php, line 88
Cake\Http\Runner::__invoke() - CORE/src/Http/Runner.php, line 65
Cake\Error\Middleware\ErrorHandlerMiddleware::__invoke() - CORE/src/Error/Middleware/ErrorHandlerMiddleware.php, line 52
Cake\Http\Runner::__invoke() - CORE/src/Http/Runner.php, line 65
Cake\Http\Runner::run() - CORE/src/Http/Runner.php, line 51
Cake\Http\Server::run() - CORE/src/Http/Server.php, line 82
[main] - ROOT/webroot/index.php, line 37



2016-10-06 00:23:24 Warning: Warning (2): array_diff() [<a href='http://php.net/function.array-diff'>function.array-diff</a>]: Argument #1 is not an array in [/home/satori/Documents/cakephp/src/Template/Productos/login.ctp, line 189]
Request URL: /
Client IP: 127.0.0.1
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE/src/Error/BaseErrorHandler.php, line 146
array_diff - [internal], line ??
include - APP/Template/Productos/login.ctp, line 189
Cake\View\View::_evaluate() - CORE/src/View/View.php, line 1008
Cake\View\View::_render() - CORE/src/View/View.php, line 967
Cake\View\View::render() - CORE/src/View/View.php, line 591
Cake\Controller\Controller::render() - CORE/src/Controller/Controller.php, line 617
Cake\Http\ActionDispatcher::_invoke() - CORE/src/Http/ActionDispatcher.php, line 128
Cake\Http\ActionDispatcher::dispatch() - CORE/src/Http/ActionDispatcher.php, line 96
Cake\Http\BaseApplication::__invoke() - CORE/src/Http/BaseApplication.php, line 83
Cake\Http\Runner::__invoke() - CORE/src/Http/Runner.php, line 65
Cake\Routing\Middleware\RoutingMiddleware::__invoke() - CORE/src/Routing/Middleware/RoutingMiddleware.php, line 52
Cake\Http\Runner::__invoke() - CORE/src/Http/Runner.php, line 65
Cake\Routing\Middleware\AssetMiddleware::__invoke() - CORE/src/Routing/Middleware/AssetMiddleware.php, line 88
Cake\Http\Runner::__invoke() - CORE/src/Http/Runner.php, line 65
Cake\Error\Middleware\ErrorHandlerMiddleware::__invoke() - CORE/src/Error/Middleware/ErrorHandlerMiddleware.php, line 52
Cake\Http\Runner::__invoke() - CORE/src/Http/Runner.php, line 65
Cake\Http\Runner::run() - CORE/src/Http/Runner.php, line 51
Cake\Http\Server::run() - CORE/src/Http/Server.php, line 82
[main] - ROOT/webroot/index.php, line 37



2016-10-06 15:09:34 Warning: Warning (2): scandir(images/capturas/The Witcher 3): failed to open dir: No such file or directory in [/home/satori/Documents/cakephp/src/Template/Productos/login.ctp, line 189]
Request URL: /
Client IP: 127.0.0.1
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE/src/Error/BaseErrorHandler.php, line 146
scandir - [internal], line ??
include - APP/Template/Productos/login.ctp, line 189
Cake\View\View::_evaluate() - CORE/src/View/View.php, line 1008
Cake\View\View::_render() - CORE/src/View/View.php, line 967
Cake\View\View::render() - CORE/src/View/View.php, line 591
Cake\Controller\Controller::render() - CORE/src/Controller/Controller.php, line 617
Cake\Http\ActionDispatcher::_invoke() - CORE/src/Http/ActionDispatcher.php, line 128
Cake\Http\ActionDispatcher::dispatch() - CORE/src/Http/ActionDispatcher.php, line 96
Cake\Http\BaseApplication::__invoke() - CORE/src/Http/BaseApplication.php, line 83
Cake\Http\Runner::__invoke() - CORE/src/Http/Runner.php, line 65
Cake\Routing\Middleware\RoutingMiddleware::__invoke() - CORE/src/Routing/Middleware/RoutingMiddleware.php, line 52
Cake\Http\Runner::__invoke() - CORE/src/Http/Runner.php, line 65
Cake\Routing\Middleware\AssetMiddleware::__invoke() - CORE/src/Routing/Middleware/AssetMiddleware.php, line 88
Cake\Http\Runner::__invoke() - CORE/src/Http/Runner.php, line 65
Cake\Error\Middleware\ErrorHandlerMiddleware::__invoke() - CORE/src/Error/Middleware/ErrorHandlerMiddleware.php, line 52
Cake\Http\Runner::__invoke() - CORE/src/Http/Runner.php, line 65
Cake\Http\Runner::run() - CORE/src/Http/Runner.php, line 51
Cake\Http\Server::run() - CORE/src/Http/Server.php, line 82
[main] - ROOT/webroot/index.php, line 37



2016-10-06 15:09:34 Warning: Warning (2): scandir() [<a href='http://php.net/function.scandir'>function.scandir</a>]: (errno 0): Success in [/home/satori/Documents/cakephp/src/Template/Productos/login.ctp, line 189]
Request URL: /
Client IP: 127.0.0.1
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE/src/Error/BaseErrorHandler.php, line 146
scandir - [internal], line ??
include - APP/Template/Productos/login.ctp, line 189
Cake\View\View::_evaluate() - CORE/src/View/View.php, line 1008
Cake\View\View::_render() - CORE/src/View/View.php, line 967
Cake\View\View::render() - CORE/src/View/View.php, line 591
Cake\Controller\Controller::render() - CORE/src/Controller/Controller.php, line 617
Cake\Http\ActionDispatcher::_invoke() - CORE/src/Http/ActionDispatcher.php, line 128
Cake\Http\ActionDispatcher::dispatch() - CORE/src/Http/ActionDispatcher.php, line 96
Cake\Http\BaseApplication::__invoke() - CORE/src/Http/BaseApplication.php, line 83
Cake\Http\Runner::__invoke() - CORE/src/Http/Runner.php, line 65
Cake\Routing\Middleware\RoutingMiddleware::__invoke() - CORE/src/Routing/Middleware/RoutingMiddleware.php, line 52
Cake\Http\Runner::__invoke() - CORE/src/Http/Runner.php, line 65
Cake\Routing\Middleware\AssetMiddleware::__invoke() - CORE/src/Routing/Middleware/AssetMiddleware.php, line 88
Cake\Http\Runner::__invoke() - CORE/src/Http/Runner.php, line 65
Cake\Error\Middleware\ErrorHandlerMiddleware::__invoke() - CORE/src/Error/Middleware/ErrorHandlerMiddleware.php, line 52
Cake\Http\Runner::__invoke() - CORE/src/Http/Runner.php, line 65
Cake\Http\Runner::run() - CORE/src/Http/Runner.php, line 51
Cake\Http\Server::run() - CORE/src/Http/Server.php, line 82
[main] - ROOT/webroot/index.php, line 37



2016-10-06 15:09:34 Warning: Warning (2): array_diff() [<a href='http://php.net/function.array-diff'>function.array-diff</a>]: Argument #1 is not an array in [/home/satori/Documents/cakephp/src/Template/Productos/login.ctp, line 189]
Request URL: /
Client IP: 127.0.0.1
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE/src/Error/BaseErrorHandler.php, line 146
array_diff - [internal], line ??
include - APP/Template/Productos/login.ctp, line 189
Cake\View\View::_evaluate() - CORE/src/View/View.php, line 1008
Cake\View\View::_render() - CORE/src/View/View.php, line 967
Cake\View\View::render() - CORE/src/View/View.php, line 591
Cake\Controller\Controller::render() - CORE/src/Controller/Controller.php, line 617
Cake\Http\ActionDispatcher::_invoke() - CORE/src/Http/ActionDispatcher.php, line 128
Cake\Http\ActionDispatcher::dispatch() - CORE/src/Http/ActionDispatcher.php, line 96
Cake\Http\BaseApplication::__invoke() - CORE/src/Http/BaseApplication.php, line 83
Cake\Http\Runner::__invoke() - CORE/src/Http/Runner.php, line 65
Cake\Routing\Middleware\RoutingMiddleware::__invoke() - CORE/src/Routing/Middleware/RoutingMiddleware.php, line 52
Cake\Http\Runner::__invoke() - CORE/src/Http/Runner.php, line 65
Cake\Routing\Middleware\AssetMiddleware::__invoke() - CORE/src/Routing/Middleware/AssetMiddleware.php, line 88
Cake\Http\Runner::__invoke() - CORE/src/Http/Runner.php, line 65
Cake\Error\Middleware\ErrorHandlerMiddleware::__invoke() - CORE/src/Error/Middleware/ErrorHandlerMiddleware.php, line 52
Cake\Http\Runner::__invoke() - CORE/src/Http/Runner.php, line 65
Cake\Http\Runner::run() - CORE/src/Http/Runner.php, line 51
Cake\Http\Server::run() - CORE/src/Http/Server.php, line 82
[main] - ROOT/webroot/index.php, line 37



